AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: networth.app Token Observer

Parameters:
  AppName:
    Type: String
    Default: networth
  DomainName:
    Type: String
    Default: networth.app
  EnvPlaidClientID:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_CLIENT_ID
  # TODO: [SECURITY] encrypt using SecureString
  EnvPlaidSecret:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_SECRET
  EnvSlackWebhook:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/SLACK_WEBHOOK_URL

Resources:
  NetWorthTokenObserverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: ../bin
      Handler: networth-token-observer
      FunctionName: networth-token-observer
      Description:  networth.app Token Observer
      Role:
        Fn::ImportValue:
          !Join [-, [ !Ref AppName, lambda, role]]
      Environment:
        Variables:
          TOKEN_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, token, table]]
          HISTORY_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, history, table]]
          TRANSACTION_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, transaction, table]]
          SNS_TOPIC_ARN:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, sns]]
          KMS_KEY_ALIAS:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, kms, alias]]
          SLACK_WEBHOOK_URL: !Ref EnvSlackWebhook
          PLAID_ENV: sandbox
          PLAID_PUBLIC_KEY: 7e599ac974fb8343f50fac8535fcf1
          PLAID_CLIENT_ID: !Ref EnvPlaidClientID
          PLAID_SECRET: !Ref EnvPlaidSecret
      Events:
        DynamoDBStreamTokenEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [-, [ !Ref AppName, token, table, stream]]
            StartingPosition: LATEST
            BatchSize: 10
