matrix:
  include:
  - language: go
    install:
    - pip install awscli --upgrade --user
    before_script: cd api
    script: go test
    before_deploy: cd ${TRAVIS_BUILD_DIR}
    deploy:
    - provider: script
      script: make deploy-api
  - language: go
    install:
    - pip install awscli --upgrade --user
    before_script: cd api/token_observer
    script: go test
    before_deploy: cd ${TRAVIS_BUILD_DIR}
    deploy:
    - provider: script
      script: make deploy-token-observer
  - language: node_js
    node_js: 10
    before_install: cd web
    install:
    - pip install awscli --upgrade --user
    - npm i
    script:
    - npm test
    - npm run build
    before_deploy:
    - aws cloudfront create-invalidation --distribution-id ${WEBAPP_DISTRIBUTION_ID}
      --paths '/*'
    - aws cloudfront create-invalidation --distribution-id ${LANDING_DISTRIBUTION_ID}
      --paths '/*'
    deploy:
    - provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: networth.app
      local-dir: "${TRAVIS_BUILD_DIR}/landing"
      acl: public_read
      skip_cleanup: true
    - provider: s3
      access_key_id: "$AWS_ACCESS_KEY_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY"
      bucket: app.networth.app
      local-dir: "${TRAVIS_BUILD_DIR}/web/build"
      acl: public_read
      skip_cleanup: true
notifications:
  slack:
    on_pull_requests: false
    on_failure: always
    # TODO: turn off success, don't care about it later on
    on_success: always
    rooms:
      secure: dEFMC9FX5OsadDdVU854GEN1ehZ5ZtwhcB64TAlhxnqqOFHC2WOg5QSThhchXC+EuzvGhy5/saM/sL2VE2dHSrn952PF9sDwa5crAOmu539X+o4or8LNqoQ/XKh/ORoZ/jyQ/+MA0YZQgzU2G+iB3k2HdjYt8xG4Clt6pB/SDJhaQKIcTyqiheMpq5Vsa1KlI8HpbC5YUIGoedffckRGFD7+2toxIMor2zp/e+fFnqvltT3rI63hjUPB/2QhsutpJI1I3L1p34xgP60t4+nZ2QvvoqEH4Xt2CijlV09sHUktz9donjXGaKMUD5x6xDlS5ydIj2VhVTUnranNqv/QkZA21ONICunq8TDl/Oqr88B/pZcze9/DVWYePJdWmv83dfoAr/K30Dej1EJWeHsA7sqmgPOrplZ2mDildHdjs7pGTnxws3AhXM3PQ3HnlUefa43rwip7Ghdc5jTH7Qrcv66zPlGbY6RQyz1IL+dMpvIFuPyRP3/XHicOzledmkoZUy1uQ+LSxBqw82ikGg8opgr5c7pvS6l/X9UPEu+j7FS4MjPxjTuPLB1y2wXx+V09DSpmduEDYVMwy2AwJ1A4FdlNMm3imgUUq36KBp/GvTO1vruSyZmwDjuHTsxyU/AI/ZtqCX4ak76UxOjRX9TwgHDImH9dZ/V0kMOq7lsOGRs=
