matrix:
  include:
    - language: go
      before_script: cd api
      script: go test
      before_deploy: cd ${TRAVIS_BUILD_DIR}
      deploy:
        - provider: script
          script: make deploy-api

    - language: node_js
      node_js: 10
      before_install: cd web
      install:
        - pip install awscli --upgrade --user
        - npm i
      script:
        - npm test
        - npm run build

      before_deploy:
        # after_deploy will run these twice
        - aws cloudfront create-invalidation --distribution-id ${WEBAPP_DISTRIBUTION_ID} --paths '/*'
        - aws cloudfront create-invalidation --distribution-id ${LANDING_DISTRIBUTION_ID} --paths '/*'

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: networth.app
          local-dir: ${TRAVIS_BUILD_DIR}/landing
          acl: public_read
          skip_cleanup: true

        - provider: s3
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          bucket: app.networth.app
          local-dir: ${TRAVIS_BUILD_DIR}/web/build
          acl: public_read
          skip_cleanup: true

