language: node_js

test: true
script: true

deploy:
  provider: s3
  access_key_id: AKIAJL6AZNUAP72O5B2Q
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: networth.app
  local-dir: landing
  acl: public_read
  region: us-east-1
  on:
    repo: networth-app/networth
