AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: networth.app DB Stream

Parameters:
  AppName:
    Type: String
    Default: networth
  DomainName:
    Type: String
    Default: networth.app
  EnvPlaidClientID:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_CLIENT_ID
  EnvPlaidSecret:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_SECRET
  EnvPlaidEnv:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_ENV
  EnvPlaidPublicKey:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_PUBLIC_KEY
  EnvSlackWebhook:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/SLACK_WEBHOOK_URL

Resources:
  NetWorthDbStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: ../bin
      Handler: networth-dbstream
      Timeout: 30
      FunctionName: networth-dbstream
      Description:  networth.app DB Stream
      Role:
        Fn::ImportValue:
          !Join [-, [ !Ref AppName, lambda, role]]
      Environment:
        Variables:
          NETWORTH_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, table]]
          SNS_TOPIC_ARN:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, sns]]
          KMS_KEY_ALIAS:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, kms, alias]]
          SLACK_WEBHOOK_URL: !Ref EnvSlackWebhook
          PLAID_ENV: !Ref EnvPlaidEnv
          PLAID_PUBLIC_KEY: !Ref EnvPlaidPublicKey
          PLAID_CLIENT_ID: !Ref EnvPlaidClientID
          PLAID_SECRET: !Ref EnvPlaidSecret
      Events:
        DynamoDBStreamEvent:
          Type: DynamoDB
          Properties:
            Stream:
              Fn::ImportValue:
                !Join [-, [ !Ref AppName, table, stream]]
            StartingPosition: LATEST
            BatchSize: 1
