[metadata]
  version = "0.0.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/plaid/plaid-go"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.13.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.8"

[[constraint]]
  name = "github.com/coreos/bbolt"
  version = "1.3.0"

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/apex/gateway"
  version = "1.1.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "2.0.0-preview.4"
