AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: networth.app REST API Lambda

Parameters:
  AppName:
    Type: String
    Default: networth
  DomainName:
    Type: String
    Default: networth.app
  EnvPlaidClientID:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_CLIENT_ID
  EnvPlaidSecret:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: /networth/PLAID_SECRET

Resources:
  # APIGatewayBasePathMapping:
  #   Type: AWS::ApiGateway::BasePathMapping
  #   Properties:
  #     BasePath: '/'
  #     DomainName: !Ref DomainName
  #     RestApiId: !Ref NetWorthFunction
  #     Stage: Prod

  NetWorthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      CodeUri: ../bin
      # sam-cli doesn't support !Ref yet :(
      # Handler: !Ref AppName
      Handler: networth
      FunctionName: networth-api
      Description:  networth.app REST API
      Environment:
        Variables:
          TOKEN_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, token, table]]
          HISTORY_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, history, table]]
          TRANSACTION_TABLE:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, transaction, table]]
          SNS_TOPIC_ARN:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, sns]]
          KMS_KEY_ALIAS:
            Fn::ImportValue:
              !Join [-, [ !Ref AppName, kms, alias]]
          PLAID_ENV: sandbox
          PLAID_PUBLIC_KEY: 7e599ac974fb8343f50fac8535fcf1
          PLAID_CLIENT_ID: !Ref EnvPlaidClientID
          PLAID_SECRET: !Ref EnvPlaidSecret
      Events:
        GetNetWorth:
          Type: Api
          Properties:
            Path: /networth
            Method: get

        # GetApiProxyResource:
        #   Type: Api
        #   Properties:
        #     Path: /{proxy+}
        #     Method: any
        #     RestApiId: !Ref ApiGatewayApi
